# Generated by Django 4.1.3 on 2024-03-27 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_api', '0002_workingpapers_delete_plaiditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingpapers',
            old_name='Abstract',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='workingpapers',
            old_name='Authors',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='workingpapers',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='workingpapers',
            name='date_entered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workingpapers',
            name='paper_url',
            field=models.URLField(default='https://www.nber.org/system/files/working_papers/w32269/w32269.pdf?utm_campaign=PANTHEON_STRIPPED&amp%3Butm_medium=PANTHEON_STRIPPED&amp%3Butm_source=PANTHEON_STRIPPED'),
            preserve_default=False,
        ),
    ]
