# Generated by Django 4.1.3 on 2024-04-01 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_api', '0003_rename_abstract_workingpapers_abstract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('movie_url', models.URLField()),
                ('date_entered', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='workingpapers',
            name='abstract',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='workingpapers',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
