# Generated by Django 4.1.3 on 2024-04-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_api', '0005_rename_movies_moviesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='rating',
            field=models.FloatField(),
        ),
    ]
