# Generated by Django 4.1.3 on 2024-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_api', '0006_alter_moviesmodel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('About', models.CharField(max_length=500)),
                ('poodcast_url', models.URLField()),
            ],
        ),
    ]
