# Generated by Django 4.1.3 on 2024-04-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_api', '0007_podcastsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcastsmodel',
            old_name='poodcast_url',
            new_name='podcast_url',
        ),
    ]
